"""Generate a .bzl file with Chromium shared library packages and a module extension.

Resolves the system library packages required by Chromium headless-shell
from Ubuntu mirrors for both amd64 and arm64 architectures, then writes
a self-contained .bzl file that consumers can commit in their repo.

Supported releases:
  - jammy (22.04): glibc 2.35, pre-time_t64 package names
  - noble (24.04): glibc 2.39, time_t64 package names
"""

import argparse
import base64
import hashlib
import json
import logging
import lzma
import os
import time
import urllib.request
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError

REQUIRED_PACKAGES_JAMMY: list[str] = [
    "libasound2",
    "libatk-bridge2.0-0",
    "libatk1.0-0",
    "libatspi2.0-0",
    "libcairo2",
    "libcups2",
    "libdbus-1-3",
    "libdrm2",
    "libexpat1",
    "libfontconfig1",
    "libfreetype6",
    "libgbm1",
    "libglib2.0-0",
    "libnspr4",
    "libnss3",
    "libnssutil3",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libpcre3",
    "libpixman-1-0",
    "libwayland-client0",
    "libwayland-server0",
    "libx11-6",
    "libxau6",
    "libxcb1",
    "libxcomposite1",
    "libxdamage1",
    "libxdmcp6",
    "libxext6",
    "libxfixes3",
    "libxkbcommon0",
    "libxrandr2",
    "libxrender1",
]

REQUIRED_PACKAGES_NOBLE: list[str] = [
    "libasound2t64",
    "libatk-bridge2.0-0t64",
    "libatk1.0-0t64",
    "libatspi2.0-0t64",
    "libcairo2",
    "libcups2t64",
    "libdbus-1-3",
    "libdrm2",
    "libexpat1",
    "libfontconfig1",
    "libfreetype6",
    "libgbm1",
    "libglib2.0-0t64",
    "libnspr4",
    "libnss3",
    "libnssutil3",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libpcre3",
    "libpixman-1-0",
    "libwayland-client0",
    "libwayland-server0",
    "libx11-6",
    "libxau6",
    "libxcb1",
    "libxcomposite1",
    "libxdamage1",
    "libxdmcp6",
    "libxext6",
    "libxfixes3",
    "libxkbcommon0",
    "libxrandr2",
    "libxrender1",
]

RELEASE_PACKAGES: dict[str, list[str]] = {
    "jammy": REQUIRED_PACKAGES_JAMMY,
    "noble": REQUIRED_PACKAGES_NOBLE,
}

UBUNTU_MIRROR_AMD64 = "http://archive.ubuntu.com/ubuntu"
UBUNTU_MIRROR_ARM64 = "http://ports.ubuntu.com/ubuntu-ports"
UBUNTU_COMPONENTS: list[str] = ["main", "universe"]

ARCH_MAP: dict[str, str] = {
    "linux-x86_64": "amd64",
    "linux-aarch64": "arm64",
}

MIRROR_MAP: dict[str, str] = {
    "amd64": UBUNTU_MIRROR_AMD64,
    "arm64": UBUNTU_MIRROR_ARM64,
}

REQUEST_HEADERS: dict[str, str] = {"User-Agent": "curl/8.7.1"}

_BZL_TEMPLATE = '''\
"""Chromium shared libraries for Playwright LD_LIBRARY_PATH support.

Debian packages providing system shared libraries required by Chromium
headless-shell on Linux.
"""

# AUTO-GENERATED by:
#
#   bazel run @rules_jupyter//playwright/ld_library_path:generate_chromium_ld_library_path -- \\
#       --output <path> --release {release}
#
# DO NOT MODIFY BY HAND.

load("@rules_jupyter//playwright/ld_library_path:ld_library_dir.bzl", "playwright_ld_library_dir_repository")
load("@rules_jupyter//tools/debian:debian_archive.bzl", "debian_archive")

CHROMIUM_LD_LIBRARY_PATH_PACKAGES = {packages}

def _chromium_ld_library_path_impl(module_ctx):
    """Create debian_archive repos and ld_library_dir repos for each platform."""

    # buildifier: disable=unused-variable
    _unused = module_ctx

    for platform, packages in CHROMIUM_LD_LIBRARY_PATH_PACKAGES.items():
        suffix = platform.replace("-", "_")
        deb_labels = []
        for pkg in packages:
            repo_name = "chromium_ld_library_path_%s_%s" % (
                pkg["name"].replace(".", "_").replace("-", "_").replace("+", "_"),
                suffix,
            )
            debian_archive(
                name = repo_name,
                urls = pkg["urls"],
                integrity = pkg.get("integrity", ""),
                sha256 = pkg.get("sha256", ""),
                build_file_content = """filegroup(name = "files", srcs = glob(["**"]), visibility = ["//visibility:public"])""",
            )
            deb_labels.append("@%s//:files" % repo_name)
        playwright_ld_library_dir_repository(
            name = "chromium_ld_library_path_%s" % suffix,
            deps = deb_labels,
        )

chromium_ld_library_path = module_extension(
    implementation = _chromium_ld_library_path_impl,
)
'''


def _workspace_root() -> Path:
    """Locate the workspace root directory."""
    if "BUILD_WORKSPACE_DIRECTORY" in os.environ:
        return Path(os.environ["BUILD_WORKSPACE_DIRECTORY"])
    return Path(__file__).parent.parent.parent


def _download_with_retry(url: str, max_retries: int = 3, delay: int = 2) -> bytes:
    """Download a URL with retries."""
    last_error: Exception | None = None
    for attempt in range(max_retries):
        try:
            req = urllib.request.Request(url, headers=REQUEST_HEADERS)
            with urllib.request.urlopen(req, timeout=60) as response:
                return response.read()  # type: ignore[no-any-return]
        except (HTTPError, URLError, TimeoutError) as e:
            last_error = e
            if attempt < max_retries - 1:
                logging.warning("Attempt %d failed for %s: %s", attempt + 1, url, e)
                time.sleep(delay * (attempt + 1))
    raise last_error  # type: ignore[misc]


def _compute_integrity(data: bytes) -> str:
    """Compute SRI integrity hash (sha256)."""
    digest = hashlib.sha256(data).digest()
    b64 = base64.b64encode(digest).decode("ascii")
    return f"sha256-{b64}"


def _parse_packages_index(content: str) -> dict[str, dict[str, str]]:
    """Parse a Debian Packages file into a dict of package_name -> fields."""
    packages: dict[str, dict[str, str]] = {}
    current: dict[str, str] = {}

    for line in content.split("\n"):
        if not line.strip():
            if "Package" in current:
                packages[current["Package"]] = current
            current = {}
            continue
        if line.startswith(" ") or line.startswith("\t"):
            continue
        if ":" in line:
            key, _, value = line.partition(":")
            current[key.strip()] = value.strip()

    if "Package" in current:
        packages[current["Package"]] = current

    return packages


def _load_packages_index(release: str, arch: str) -> dict[str, dict[str, str]]:
    """Download and parse the Ubuntu Packages index for an architecture."""
    mirror = MIRROR_MAP[arch]
    all_packages: dict[str, dict[str, str]] = {}

    for component in UBUNTU_COMPONENTS:
        url = f"{mirror}/dists/{release}/{component}" f"/binary-{arch}/Packages.xz"
        logging.info("Downloading packages index: %s", url)

        data = _download_with_retry(url)
        content = lzma.decompress(data).decode("utf-8")
        packages = _parse_packages_index(content)
        all_packages.update(packages)
        logging.info(
            "Loaded %d packages from %s/%s",
            len(packages),
            release,
            component,
        )

    return all_packages


def _resolve_packages(
    required: list[str],
    packages_index: dict[str, dict[str, str]],
    arch: str,
) -> list[dict[str, Any]]:
    """Resolve required package names to .deb URLs and download for hashing."""
    mirror = MIRROR_MAP[arch]
    resolved: list[dict[str, Any]] = []

    for pkg_name in required:
        if pkg_name not in packages_index:
            logging.warning("Package %s not found for %s, skipping", pkg_name, arch)
            continue

        pkg_info = packages_index[pkg_name]
        filename = pkg_info.get("Filename")
        if not filename:
            logging.warning("Package %s has no Filename field, skipping", pkg_name)
            continue

        url = f"{mirror}/{filename}"
        logging.info("Downloading %s (%s)", pkg_name, url)

        data = _download_with_retry(url)
        integrity = _compute_integrity(data)

        resolved.append(
            {
                "name": pkg_name,
                "urls": [url],
                "integrity": integrity,
            }
        )

        logging.info("  %s -> %s", pkg_name, integrity)

    return resolved


def _format_packages_dict(
    packages_by_platform: dict[str, list[dict[str, Any]]],
) -> str:
    """Format the packages dict as a Starlark literal."""
    lines: list[str] = ["{\n"]

    for platform, packages in sorted(packages_by_platform.items()):
        lines.append(f'    "{platform}": [\n')
        for pkg in packages:
            lines.append("        {\n")
            lines.append(f'            "integrity": "{pkg["integrity"]}",\n')
            lines.append(f'            "name": "{pkg["name"]}",\n')
            lines.append(f"            \"urls\": {json.dumps(pkg['urls'])},\n")
            lines.append("        },\n")
        lines.append("    ],\n")

    lines.append("}")
    return "".join(lines)


def _find_module_bazel(start: Path) -> Path | None:
    """Walk up from start to find MODULE.bazel."""
    current = start.resolve()
    while True:
        candidate = current / "MODULE.bazel"
        if candidate.is_file():
            return candidate
        parent = current.parent
        if parent == current:
            return None
        current = parent


def _compute_label(output_path: Path, module_bazel: Path) -> str:
    """Compute the Bazel label for a file relative to MODULE.bazel."""
    workspace_root = module_bazel.parent
    rel = output_path.resolve().relative_to(workspace_root)
    package = str(rel.parent)
    if package == ".":
        return f"//:{rel.name}"
    return f"//{package}:{rel.name}"


def main() -> None:
    """Generate a .bzl file with shared library packages and module extension."""
    logging.basicConfig(
        format="%(levelname)s: %(message)s",
        level=logging.INFO,
    )

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output path for the generated .bzl file.",
    )
    parser.add_argument(
        "--release",
        choices=sorted(RELEASE_PACKAGES.keys()),
        default="jammy",
        help="Ubuntu release to resolve packages from (default: jammy)",
    )
    args = parser.parse_args()

    required_packages = RELEASE_PACKAGES[args.release]
    packages_by_platform: dict[str, list[dict[str, Any]]] = {}

    for platform, arch in sorted(ARCH_MAP.items()):
        logging.info(
            "=== Resolving packages for %s (%s, %s) ===",
            platform,
            arch,
            args.release,
        )
        packages_index = _load_packages_index(args.release, arch)
        resolved = _resolve_packages(required_packages, packages_index, arch)
        packages_by_platform[platform] = resolved
        logging.info(
            "Resolved %d/%d packages for %s",
            len(resolved),
            len(required_packages),
            platform,
        )

    content = _BZL_TEMPLATE.format(
        release=args.release,
        packages=_format_packages_dict(packages_by_platform),
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    logging.info("Wrote %s", args.output)

    module_bazel = _find_module_bazel(args.output.parent)
    if module_bazel:
        label = _compute_label(args.output, module_bazel)
        repo_names = [
            f"chromium_ld_library_path_{p.replace('-', '_')}"
            for p in sorted(packages_by_platform.keys())
        ]
        repos_str = ",\n    ".join(f'"{r}"' for r in repo_names)
        print()
        print("# Add to MODULE.bazel:")
        print(
            f'chromium_ld_library_path = use_extension("{label}",'
            ' "chromium_ld_library_path")'
        )
        print("use_repo(")
        print("    chromium_ld_library_path,")
        print(f"    {repos_str},")
        print(")")
        print()
    else:
        logging.warning(
            "Could not find MODULE.bazel above %s; "
            "unable to compute label for MODULE.bazel snippet.",
            args.output,
        )


if __name__ == "__main__":
    main()
